### ISSUE TITLE
"Could not discover provider while making request: method:eth_estimateGas"

### ISSUE THREAD

**Issue by StrixSC** [chainflag/eth-challenge-base#17]
Hello! 

I am getting the error in the title when trying to deploy a challenge contract when running the example in the `/example` folder. 
I am using the PoA geth private network inside of the /geth directory as my Web3 RTC provider.

The entire trace of the error is the following: 

```
nc 127.0.0.1 20000                                                                                    ✔  10s  
We design a pretty easy contract challenge. Enjoy it!
Your goal is to make isSolved() function returns true!

[1] - Create an account which will be used to deploy the challenge contract
[2] - Deploy the challenge contract using your generated account
[3] - Get your flag once you meet the requirement
[4] - Show the contract source code
[-] input your choice: 1
[+] deployer account: 0x7dCC0f237b795E718e16591bB00ACB8e2121FfD2
[+] token: v4.local.v-vOGz-M2GYzBik-EAADyrkoDaJLDtJc68TCyByYn7CFUsnHalmocKi9EzhjsXGMOu8UKrT-GKFKK7N2S4DEZd8Kmdya1ilUhn4K5Ei1yWu5cj7XMkt47aalZt60Qc98VhHGgOIn0ZzAMqtBi0_qqFZGfgzd_gEloBHaxrbzvyMIsg
Traceback (most recent call last):
  File "/home/ctf/run.py", line 50, in <module>
    main()
  File "/home/ctf/run.py", line 46, in main
    sys.exit(actions[choice].handler())
  File "/home/ctf/eth_challenge_base/action.py", line 67, in action
    or self._contract.deploy.estimate_gas(constructor.args)
  File "/home/ctf/eth_challenge_base/utils/eth.py", line 101, in estimate_gas
    return self._instance.constructor(*args).estimateGas()
  File "/usr/local/lib/python3.9/site-packages/eth_utils/decorators.py", line 18, in _wrapper
    return self.method(obj, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/web3/contract.py", line 643, in estimateGas
    return self.web3.eth.estimate_gas(
  File "/usr/local/lib/python3.9/site-packages/web3/eth.py", line 735, in estimate_gas
    return self._estimate_gas(transaction, block_identifier)
  File "/usr/local/lib/python3.9/site-packages/web3/module.py", line 57, in caller
    result = w3.manager.request_blocking(method_str,
  File "/usr/local/lib/python3.9/site-packages/web3/manager.py", line 186, in request_blocking
    response = self._make_request(method, params)
  File "/usr/local/lib/python3.9/site-packages/web3/manager.py", line 147, in _make_request
    return request_func(method, params)
  File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
  File "/usr/local/lib/python3.9/site-packages/web3/middleware/formatting.py", line 76, in apply_formatters
    response = make_request(method, params)
  File "/usr/local/lib/python3.9/site-packages/web3/middleware/gas_price_strategy.py", line 90, in middleware
    return make_request(method, params)
  File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
  File "/usr/local/lib/python3.9/site-packages/web3/middleware/formatting.py", line 74, in apply_formatters
    response = make_request(method, formatted_params)
  File "/usr/local/lib/python3.9/site-packages/web3/middleware/attrdict.py", line 33, in middleware
    response = make_request(method, params)
  File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
  File "/usr/local/lib/python3.9/site-packages/web3/middleware/formatting.py", line 74, in apply_formatters
    response = make_request(method, formatted_params)
  File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
  File "/usr/local/lib/python3.9/site-packages/web3/middleware/formatting.py", line 74, in apply_formatters
    response = make_request(method, formatted_params)
  File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
  File "/usr/local/lib/python3.9/site-packages/web3/middleware/formatting.py", line 74, in apply_formatters
    response = make_request(method, formatted_params)
  File "/usr/local/lib/python3.9/site-packages/web3/middleware/buffered_gas_estimate.py", line 40, in middleware
    return make_request(method, params)
  File "/usr/local/lib/python3.9/site-packages/web3/providers/auto.py", line 94, in make_request
    return self._proxy_request(method, params)
  File "/usr/local/lib/python3.9/site-packages/web3/providers/auto.py", line 106, in _proxy_request
    raise CannotHandleRequest(
web3.exceptions.CannotHandleRequest: Could not discover provider while making request: method:eth_estimateGas
params:({'data': '0x608060405234801561001057600080fd5b506040516106b53803806106b583398101604081905261002f916100e2565b8051610042906000906020840190610049565b5050610202565b828054610055906101b1565b90600052602060002090601f01602090048101928261007757600085556100bd565b82601f1061009057805160ff19168380011785556100bd565b828001600101855582156100bd579182015b828111156100bd5782518255916020019190600101906100a2565b506100c99291506100cd565b5090565b5b808211156100c957600081556001016100ce565b600060208083850312156100f557600080fd5b82516001600160401b038082111561010c57600080fd5b818501915085601f83011261012057600080fd5b815181811115610132576101326101ec565b604051601f8201601f19908116603f0116810190838211818310171561015a5761015a6101ec565b81604052828152888684870101111561017257600080fd5b600093505b828410156101945784840186015181850187015292850192610177565b828411156101a55760008684830101525b98975050505050505050565b600181811c908216806101c557607f821691505b602082108114156101e657634e487b7160e01b600052602260045260246000fd5b50919050565b634e487b7160e01b600052604160045260246000fd5b6104a4806102116000396000f3fe608060405234801561001057600080fd5b50600436106100415760003560e01c806364d98f6e14610046578063a413686214610063578063cfae321714610078575b600080fd5b61004e61008d565b60405190151581526020015b60405180910390f35b610076610071366004610251565b61010f565b005b610080610126565b60405161005a91906103ba565b6000806040518060400160405280600e81526020016d48656c6c6f436861696e466c616760901b815250905060006040516020016100cb919061031e565b60405160208183030381529060405280519060200120816040516020016100f29190610302565b604051602081830303815290604052805190602001201491505090565b80516101229060009060208401906101b8565b5050565b6060600080546101359061041d565b80601f01602080910402602001604051908101604052809291908181526020018280546101619061041d565b80156101ae5780601f10610183576101008083540402835291602001916101ae565b820191906000526020600020905b81548152906001019060200180831161019157829003601f168201915b5050505050905090565b8280546101c49061041d565b90600052602060002090601f0160209004810192826101e6576000855561022c565b82601f106101ff57805160ff191683800117855561022c565b8280016001018555821561022c579182015b8281111561022c578251825591602001919060010190610211565b5061023892915061023c565b5090565b5b80821115610238576000815560010161023d565b60006020828403121561026357600080fd5b813567ffffffffffffffff8082111561027b57600080fd5b818401915084601f83011261028f57600080fd5b8135818111156102a1576102a1610458565b604051601f8201601f19908116603f011681019083821181831017156102c9576102c9610458565b816040528281528760208487010111156102e257600080fd5b826020860160208301376000928101602001929092525095945050505050565b600082516103148184602087016103ed565b9190910192915050565b600080835481600182811c91508083168061033a57607f831692505b602080841082141561035a57634e487b7160e01b86526022600452602486fd5b81801561036e576001811461037f576103ac565b60ff198616895284890196506103ac565b60008a81526020902060005b868110156103a45781548b82015290850190830161038b565b505084890196505b509498975050505050505050565b60208152600082518060208401526103d98160408501602087016103ed565b601f01601f19169190910160400192915050565b60005b838110156104085781810151838201526020016103f0565b83811115610417576000848401525b50505050565b600181811c9082168061043157607f821691505b6020821081141561045257634e487b7160e01b600052602260045260246000fd5b50919050565b634e487b7160e01b600052604160045260246000fdfea2646970667358221220fe5bbadaeb2595dc6e73ff3c1690c998b4933dbda3a07bca27c8d6e68e5dfbe264736f6c634300080700330000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000000568656c6c6f000000000000000000000000000000000000000000000000000000'},)
```
**Expected behaviour:**
The contract should be deployed on the network and the token should be returned.

**Actual behaviour:**
The program crashes and no contract is deployed.

**Steps to reproduce:**
1. Follow the steps in the `/geth` README to create an account, a genesis block and start the PoA network using `docker-compose up`.
2. Write the following inside of the `/example/.env` file: `WEB3_PROVIDER_URI=http://localhost:8545`
3. Run `docker-compose up` in the `/example` folder.
4. Connect to the challenge server with netcat: `nc 127.0.0.1 20000`
5. Select the first option to deploy a new challenge contract

I thought that maybe the `eth_estimateGas` was not whitelisted through nginx, but it is.

The network running did not show any trace of the request or the error. Please let me know if I missed anything or if there are any other logs that you need.

**Comment by iczc** [comment]
### Reason
> Write the following inside of the /example/.env file: WEB3_PROVIDER_URI=http://localhost:8545

Since the PoA geth private network and eth-challenge-base are not in the same docker network,  the `http://localhost:8545` of eth-challenge-base is not connected to geth's JSON-RPC, it' s just the loopback address of the container itself.

### Solution
Use lan IP address or public IP address instead of localhost.

**Comment by StrixSC** [comment]
Seems to work! I just put everything in the same `docker-compose.yml` file in the end. Thanks for the help! :smile:

**Comment by iczc** [comment]
I just migrated PoA geth environment from another repositor to `geth` folder, and I'm going to integrate it with the eth-challenge-base to simplify the contract challenge deployment. Any ideas or suggestions please let me know!

**Comment by StrixSC** [comment]
So far the setup was really smooth and the documentation was really thorough, I didn't have any issues at all (except for this mistake by my part obviously :sweat_smile:).
I will let you know if I have any suggestions, thanks for your work!
